<% require "dotenv"; Dotenv.load(".env") %>

service: demo-go-echo
image: gambala/demo-go-echo
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: echo.gambala.pro
  app_port: 1323
  healthcheck:
    interval: 10
    path: /
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: arm64
